### ISSUE TITLE
Dynamic sitemap for public page

### ISSUE THREAD

**Issue by mazipan** [mazipan/tanyaaja#101]
**Is your feature request related to a problem? Please describe.**
We already have a static sitemap for a static URL, but still doesn't have for the dynamic one.

We need generate the dynamic sitemap for public question/question submission page (check on https://www.tanyaaja.in/eksplor), e.g:

- https://www.tanyaaja.in/p/mzp
- https://www.tanyaaja.in/p/zain
- https://www.tanyaaja.in/p/fatihkalifa

**Describe the solution you'd like**

- Select all users, especially the one that already marked as public users
- Generate the sitemap
- Adding the path to the sitemap index
- https://nextjs.org/learn/seo/crawling-and-indexing/xml-sitemaps

**Comment by adjieguntoro-dev** [comment]
do we need to combine the existing sitemap and the dynamic into a single sitemap, mas?

**Comment by mazipan** [comment]
I already create an index sitemap, just need to adding new entry on the sitemap index
