### ISSUE TITLE
Show button copy & redirect only when question is accessible

### ISSUE THREAD

**Issue by mazipan** [mazipan/tanyaaja#21]
**Describe the bug**
As mentioned in title

**To Reproduce**
1. Go to account page: https://www.tanyaaja.in/account
2. See some question card
3. Check the one that is not accessible by the public user
4. Button copy and redirect is shown

**Expected behavior**

Only shown when accessible

**Screenshots**

<img width="457" alt="Screenshot 2023-10-10 at 14 54 15" src="https://github.com/mazipan/tanyaaja/assets/7221389/fa948c79-bd93-4da4-9284-b8c2ce9bd3c2">

**Comment by thezeeshann** [comment]
@mazipan can you assign me this issue
