### ISSUE TITLE
Add message box to remind user about showing their data in the eksplor page

### ISSUE THREAD

**Issue by mazipan** [mazipan/tanyaaja#22]
**Is your feature request related to a problem? Please describe.**

Some users are not shown in the eksplor page, while it might intended, maybe we need to remind them about this feature.

**Describe the solution you'd like**

Add a message box in account page (https://www.tanyaaja.in/account) when the user still not allowing to be accessed in eksplor page

**Additional context**
The message box can be dismiss and should not be shown again for at least a week or a month

**Comment by Namchee** [comment]
Mas @mazipan, can I tackle this issue?
