### ISSUE TITLE
Reset form after sending question

### ISSUE THREAD

**Issue by mazipan** [mazipan/tanyaaja#25]
**Describe the bug**
The form not being cleared after sending question, make the user can send the same question twice

**To Reproduce**
1. Go to any question page, https://www.tanyaaja.in/p/mzp
2. Type question
3. Click submit 

**Expected behavior**
Form should be cleared

**Additional context**
If it's possible, also avoid sending the same question twice, by saving the last question to the session storage and check it before submitting to the server

**Comment by Rounak-stha** [comment]
I'm taking a look at this.

**Comment by mazipan** [comment]
You can try to use `form.reset()` from `react-hook-form`

**Comment by Rounak-stha** [comment]
Hey, I got confused how the page at p/[slug] work.
Should there be an already registered user?

**Comment by mazipan** [comment]
Closed in #30
