### ISSUE TITLE
Frontpage container didn't do so well with 4K monitors

### ISSUE THREAD

**Issue by aldy505** [mazipan/tanyaaja#28]
**Describe the bug**
On the frontpage, there should be a container to contain the maximum width set by the CSS, so the person who open the website on a bigger monitor wouldn't be needing to move their heads left and right to see all the contents.

**To Reproduce**
1. Buy a 4K monitor
2. Open tanyaaja.in frontpage
3. Use normal scaling (4K 100%)

**Expected behavior**

It should not be spread wide, it should have some container that set a certain maximum width

**Screenshots**

1080p (basically a 4K monitor, scaled to 200%)
![image](https://github.com/mazipan/tanyaaja/assets/7274326/b7462c83-b62e-4af8-98d1-5b60166063ab)

4K
![image](https://github.com/mazipan/tanyaaja/assets/7274326/831a1f44-569c-4345-8491-41b3b45e1335)

**Additional context**
None

**Comment by karokari** [comment]
Mas @mazipan can you assign me for fix this issues?
