### ISSUE TITLE
Public Page Card link overflows

### ISSUE THREAD

**Issue by Namchee** [mazipan/tanyaaja#39]
**Describe the bug**

Public page card (`Laman Publik`) contains a link that can possibly overflow if the account name is long.

Also, it seems like there's a visually hidden arrow element with dark colors on dark background.

**To Reproduce**

1. Go to `https://www.tanyaaja.in/account`

**Expected behavior**

Links shouldn't overflow, it should either wrap around the card or the card should resize to fit the contents.

**Screenshots**

![Screenshot from 2023-10-11 21-06-38](https://github.com/mazipan/tanyaaja/assets/32661241/0ca95a64-32bd-40e4-8573-2e576583c9c4)

![Screenshot from 2023-10-11 21-06-58](https://github.com/mazipan/tanyaaja/assets/32661241/69bdf3c5-6cb4-4033-aaa9-693dfc47bb6a)

**Comment by VishalMyla** [comment]
Assign this issue to me .

**Comment by Namchee** [comment]
Weird, I can't reproduce this at all in my local machine. It gets truncated correctly and the icon is visible.

![Screenshot from 2023-10-13 11-29-41](https://github.com/mazipan/tanyaaja/assets/32661241/f2c8b597-4167-476a-9026-e289da0a8747)
