### ISSUE TITLE
Shorter nanoid for question

### ISSUE THREAD

**Issue by mazipan** [mazipan/tanyaaja#46]
**Is your feature request related to a problem? Please describe.**
When submitting question, we generate a random id using nanoid, but it still generating too long ID (around 21char).

Even though it is better, I guess for our case it's better to generate shorter id instead.

**Describe the solution you'd like**

See https://github.com/steven-tey/dub/blob/main/packages/utils/src/index.ts#L65-L68

**Comment by theodorusclarence** [comment]
i can take this

**Comment by theodorusclarence** [comment]
@mazipan can I ask why the need of customAlphabet? i believe nanoId is already URL safe and we can just call `nanoid(7)`

**Comment by mazipan** [comment]
Not sure, just found out that `dub` using it. Maybe to eliminate the special char such as `-`, `_`, etc.
No preference from me
