### ISSUE TITLE
Possibility to move the action to the list

### ISSUE THREAD

**Issue by mazipan** [mazipan/tanyaaja#56]
**Is your feature request related to a problem? Please describe.**
On the question list (https://www.tanyaaja.in/account), you need to Click "Selengkapnya" and open the dialog to do "Tandai Sudah Dijawab" and "Beri akses publik".

The reason is because I want to reduce too many buttons in the list it self.

But this decision leading to too many steps for user to do some actions.

**Describe the solution you'd like**
Not sure, but thinking to move some actions to the list. Maybe not all, but one of them maybe can be move out.

<img width="532" alt="Screenshot 2023-10-13 at 11 27 05" src="https://github.com/mazipan/tanyaaja/assets/7221389/e00f0946-7654-4fab-a371-83795dff5980">

**Comment by fandok** [comment]
Can I take at look for these issue mas? I want to try also whether the "Beri Akses Publik" button or the "Tandai sudah dijawab" button will be better on the list

**Comment by mazipan** [comment]
If it's possible maybe move out the function from the component.
Maybe using Hooks or utils, so it's easier to plug into different component in the future.

**Comment by mazipan** [comment]
Also if you decide to move the "Mark As Done" button, maybe it will conflict with enhancement in #69 

You don't need to work all of them in a single PR.
Just be aware of other task for now

**Comment by fandok** [comment]
just see the post, okay mas
