### ISSUE TITLE
Alert layout in Notification Setting Page is overflowed

### ISSUE THREAD

**Issue by mazipan** [mazipan/tanyaaja#61]
**Describe the bug**

The layout inside the Alert Box is overflowed in small screen (mobile device)

**To Reproduce**

1. Go to https://www.tanyaaja.in/account/settings/notification
2. Use small screen, you can use responsive emulator in your Browser
3. Check the Alert Box
4. See the word inside the Alert Box

**Expected behavior**
Should not overflowed

**Screenshots**

<img width="356" alt="Screenshot 2023-10-13 at 17 04 30" src="https://github.com/mazipan/tanyaaja/assets/7221389/951938a3-71ee-4888-a931-206d40b6bac9">

**Additional Context**

Seems need to removing the class `flex items-center gap-2` in https://github.com/mazipan/tanyaaja/blob/master/src/modules/AccountSettings/SettingNotif/SettingTelegram.tsx#L164-L182

**Comment by yashj09** [comment]
can you assign me this

**Comment by saakshiraut28** [comment]
I would like to work on this issue.
