### ISSUE TITLE
Telegram message not formatted correctly 

### ISSUE THREAD

**Issue by mazipan** [mazipan/tanyaaja#64]
**Describe the bug**
Several times ago, we develop a telegram notification via Bot.

But the message seems not formatted properly.

**To Reproduce**

1. Activate your Telegram Notification
2. Try to send message
3. Check the message format

**Expected behavior**

The markdown message should be formatted properly.

**Screenshots**
![Screenshot_20231013-200422_Telegram](https://github.com/mazipan/tanyaaja/assets/7221389/cae465de-227c-43ee-be81-614491f5b26e)

**Additional context**
Possibly need to add additional parameter when sending the message.

```ts
{
 parse_mode: markdown',
 disable_web_page_preview: true
}
```

Reference: https://core.telegram.org/bots/api#sendmessage

**Comment by aldy505** [comment]
`parse_mode` harusnya HTML. terus ngoding old school HTML biasa. see https://core.telegram.org/api/entities#allowed-entities
