### ISSUE TITLE
Avoid sending the same question from frontend

### ISSUE THREAD

**Issue by mazipan** [mazipan/tanyaaja#65]
**Is your feature request related to a problem? Please describe.**
Not sure if it's intended or not, but I found that someone sending the same question to different person.

In another case, to the same person.

**Describe the solution you'd like**
My idea is saving the last sent question to the session storage/local storage. Before sending it, validate in frontend. Make sure it's not the same with the previous one.

**Comment by fandok** [comment]
Mas Irfan, I would like to handle this issue.
From your solution, i think the implementation would be:
1. Store sent question to the session storage
2. When another question asked, validated the question with the one in the session storage

Another issue to tackle is maybe to disable the send question button when question asked to prevent the double question

**Comment by fandok** [comment]
Just finish the implementation mas @mazipan

Had busy at work so I can only do it right now
