### ISSUE TITLE
Add confirmation dialog before Mark as Done

### ISSUE THREAD

**Issue by mazipan** [mazipan/tanyaaja#69]
**Is your feature request related to a problem? Please describe.**

We have a button to mark a button as an answered/done.

This action will hide the question from the owner.

There's no way to revert this action since we decided to not showing the question with a Done status.

Using this information, we need to add confirmation before executing the action. To make sure it's not accidentally clicked.

**Describe the solution you'd like**
Adding a confirmation dialog before executing the action.

**Comment by joshith3501** [comment]
Hey, I would like to try implementing this. Can you assign this issue to me?
