### ISSUE TITLE
Double icon sets

### ISSUE THREAD

**Issue by mazipan** [mazipan/tanyaaja#7]
Currently we have two icon sets installed 

- https://www.radix-ui.com/icons
- https://lucide.dev/icons/

Seems Shadcn UI by default is using `lucide`, so it's better to follow the same decision.

**Comment by fandok** [comment]
Mas @mazipan can I take a look for this one?

**Comment by mazipan** [comment]
You can hit DM on me in Twitter to faster setup `.env` in the local @fandok

**Comment by mazipan** [comment]
At least in 20 places

<img width="464" alt="Screenshot 2023-10-12 at 16 53 04" src="https://github.com/mazipan/tanyaaja/assets/7221389/2ed6b5d2-6f44-4684-a269-243339256e19">

**Comment by fahmiidris** [comment]
Hi mas @mazipan, can I get a `.env` file for faster setup? I can't DM you on Twitter because I'm not a verified user. 🥹 this is my twitter https://twitter.com/fahmiidris_dev.

**Comment by fandok** [comment]
@mazipan i submitted the PR for the icons, if you have time kindly check mas on #62 

Thank you 🙏🏻
