### ISSUE TITLE
Add contribution guidelines 

### ISSUE THREAD

**Issue by mazipan** [mazipan/tanyaaja#70]
Refer to wargabantuwarga https://github.com/kawalcovid19/wargabantuwarga.com

**Comment by sirish123** [comment]
could u assign me this issue!

**Comment by mazipan** [comment]
I am not assigning any issue, just open Draft PR

**Comment by sirish123** [comment]
how detailed would u want it to be? the link you provided seems to be comprehensive would you like the same?
also should i add to the Readme or create a seperate contributing.md

**Comment by mazipan** [comment]
Yes, follow the same
