### ISSUE TITLE
Adding more gradient

### ISSUE THREAD

**Issue by mazipan** [mazipan/tanyaaja#79]
**Is your feature request related to a problem? Please describe.**

Currently we have 4 gradient, maybe adding more choices, 1 or two more.

Check https://hypercolor.dev/

**Describe the solution you'd like**

Copy name, tailwind classes and CSS native from hypercolor.dev

I don't have any preferences, but  I like the diversity. So please choose the theme that have very different vibes from the existing one.

**Comment by Parthasarathip123** [comment]
can you please assign me this @mazipan
