### ISSUE TITLE
Showing total count of user registered in homepage

### ISSUE THREAD

**Issue by mazipan** [mazipan/tanyaaja#88]
**Is your feature request related to a problem? Please describe.**

Adding some stats in the homepage will be cool. The numbers maybe not need to be real-time.

**Describe the solution you'd like**
Some articles said we should use 
- Search API to get the total: https://developers.notion.com/reference/post-search
- Or Page Property to get the unique values https://developers.notion.com/reference/retrieve-a-page-property

**Additional context**
- Do not exposing any data except the count itself.
- Implement cache?

**Comment by kliu57** [comment]
I would like to work on this issue.
By homepage do you mean this page?
![image](https://github.com/mazipan/tanyaaja/assets/98062538/ec790783-da30-4f88-a1af-8b0ca379d66f)
Where on this page would you like the user count displayed?

Also, can you give more information about the implement cache part?

**Comment by mazipan** [comment]
No, homepage is https://www.tanyaaja.in/.
The landing page.

**Comment by kliu57** [comment]
Ok I understand. Where in the landing page do you want it, and are there some wordings you want to provide me?

**Comment by mazipan** [comment]
The section's title is: Total Pengguna Terdaftar
